modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"

[[mods]] #mandatory
modId="villagerrefresh" #mandatory
version="1.0" #mandatory
displayName="Villager Refresh" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="examplemod.png" #optional
credits="Me, Alex Thimineur" #optional
authors="HutchCS" #optional
description='''
A 1.19 Villager Trade Refresh mod
'''
